name = "ytb-studio"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
routes = [
  { pattern = "your-domain.com", custom_domain = true },
]

[assets]
directory = "public"
binding = "ASSETS"

[observability]
enabled = true
